-- ============================================================
-- Tech Wear — Modelo físico (PostgreSQL 16+)
--
-- Une três fontes:
--   * apresentação de infraestrutura (tabelas usuarios/produtos/pedidos/
--     itens_pedido, procedures e queries de exemplo);
--   * modelo lógico (categorias, modalidades, estilos, atributos, imagens,
--     processamento de IA, favoritos, recomendações, preferências);
--   * o que o site já faz (tamanhos, cor HEX, frete, cupons, formas de
--     pagamento, parcelamento, nota fiscal).
--
-- Convenção: tabelas no plural, PK "id", FK "<entidade>_id".
-- Assim as queries e procedures da apresentação rodam sem alteração.
-- Script idempotente: pode ser executado mais de uma vez.
-- ============================================================

SET client_min_messages = warning;
BEGIN;

CREATE EXTENSION IF NOT EXISTS citext;

-- ------------------------------------------------------------
-- Tipos enumerados
-- ------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'genero_produto') THEN
        CREATE TYPE genero_produto AS ENUM ('masculino', 'feminino', 'unissex');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'status_usuario') THEN
        CREATE TYPE status_usuario AS ENUM ('ativo', 'inativo', 'bloqueado');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'status_pedido') THEN
        CREATE TYPE status_pedido AS ENUM
            ('aberto', 'aguardando_pagamento', 'pago', 'enviado', 'entregue', 'cancelado');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'metodo_pagamento') THEN
        CREATE TYPE metodo_pagamento AS ENUM ('credito', 'debito', 'pix', 'boleto');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'status_pagamento') THEN
        CREATE TYPE status_pagamento AS ENUM ('pendente', 'aprovado', 'recusado', 'estornado', 'expirado');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tipo_entrega') THEN
        CREATE TYPE tipo_entrega AS ENUM ('padrao', 'expressa');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'status_entrega') THEN
        CREATE TYPE status_entrega AS ENUM
            ('aguardando_envio', 'em_transito', 'entregue', 'devolvido', 'extraviado');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tipo_endereco') THEN
        CREATE TYPE tipo_endereco AS ENUM ('residencial', 'comercial', 'outro');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tipo_recomendacao') THEN
        CREATE TYPE tipo_recomendacao AS ENUM
            ('similaridade_visual', 'mesma_cor', 'complementar', 'preferencia_estilo');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tipo_dado_atributo') THEN
        CREATE TYPE tipo_dado_atributo AS ENUM ('texto', 'numero', 'booleano', 'lista');
    END IF;
END$$;

-- Atualiza a coluna atualizado_em em cada UPDATE
CREATE OR REPLACE FUNCTION set_atualizado_em() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.atualizado_em := now();
    RETURN NEW;
END;
$$;

-- ============================================================
-- Usuários, papéis e endereços
-- ============================================================
CREATE TABLE IF NOT EXISTS usuarios (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(150) NOT NULL,
    email         CITEXT       NOT NULL UNIQUE,
    senha_hash    VARCHAR(255) NOT NULL,          -- bcrypt/argon2, nunca texto ou base64
    telefone      VARCHAR(20),
    bio           VARCHAR(500),
    status        status_usuario NOT NULL DEFAULT 'ativo',
    criado_em     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    atualizado_em TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS papeis (
    id        SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      VARCHAR(30)  NOT NULL UNIQUE,       -- admin, cliente
    descricao VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS usuario_papeis (
    usuario_id BIGINT   NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    papel_id   SMALLINT NOT NULL REFERENCES papeis(id)   ON DELETE RESTRICT,
    PRIMARY KEY (usuario_id, papel_id)
);

CREATE TABLE IF NOT EXISTS enderecos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT       NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    logradouro  VARCHAR(200) NOT NULL,
    numero      VARCHAR(20)  NOT NULL,
    complemento VARCHAR(100),
    bairro      VARCHAR(100) NOT NULL,
    cidade      VARCHAR(100) NOT NULL,
    estado      CHAR(2)      NOT NULL CHECK (estado ~ '^[A-Z]{2}$'),
    cep         CHAR(8)      NOT NULL CHECK (cep ~ '^[0-9]{8}$'),
    pais        CHAR(2)      NOT NULL DEFAULT 'BR',
    tipo        tipo_endereco NOT NULL DEFAULT 'residencial',
    principal   BOOLEAN      NOT NULL DEFAULT false,
    criado_em   TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_enderecos_usuario ON enderecos (usuario_id);
-- No máximo um endereço principal por usuário
CREATE UNIQUE INDEX IF NOT EXISTS ux_enderecos_principal
    ON enderecos (usuario_id) WHERE principal;

-- ============================================================
-- Catálogo
-- ============================================================
CREATE TABLE IF NOT EXISTS categorias (
    id               SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_pai_id SMALLINT REFERENCES categorias(id) ON DELETE RESTRICT,
    slug             VARCHAR(40)  NOT NULL UNIQUE,   -- valor usado pelo site (camisetas, calcas...)
    nome             VARCHAR(80)  NOT NULL,
    descricao        VARCHAR(300),
    ativo            BOOLEAN      NOT NULL DEFAULT true,
    CHECK (categoria_pai_id IS NULL OR categoria_pai_id <> id)
);

-- Esporte/modalidade do site: corrida, basquete, academia, todos
CREATE TABLE IF NOT EXISTS modalidades (
    id        SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug      VARCHAR(40)  NOT NULL UNIQUE,
    nome      VARCHAR(80)  NOT NULL,
    descricao VARCHAR(300),
    ativo     BOOLEAN      NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS estilos (
    id        SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug      VARCHAR(40)  NOT NULL UNIQUE,
    nome      VARCHAR(80)  NOT NULL,
    descricao VARCHAR(300),
    ativo     BOOLEAN      NOT NULL DEFAULT true
);

-- Citado na área administrativa da apresentação
CREATE TABLE IF NOT EXISTS fornecedores (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razao_social VARCHAR(200) NOT NULL,
    cnpj      CHAR(14)     NOT NULL UNIQUE CHECK (cnpj ~ '^[0-9]{14}$'),
    email     CITEXT,
    telefone  VARCHAR(20),
    ativo     BOOLEAN      NOT NULL DEFAULT true,
    criado_em TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS produtos (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku            VARCHAR(40)    NOT NULL UNIQUE,
    nome           VARCHAR(150)   NOT NULL,
    descricao      TEXT,
    categoria_id   SMALLINT       NOT NULL REFERENCES categorias(id)  ON DELETE RESTRICT,
    modalidade_id  SMALLINT       REFERENCES modalidades(id)          ON DELETE RESTRICT,
    estilo_id      SMALLINT       REFERENCES estilos(id)              ON DELETE SET NULL,
    fornecedor_id  BIGINT         REFERENCES fornecedores(id)         ON DELETE SET NULL,
    preco          NUMERIC(12,2)  NOT NULL CHECK (preco > 0),
    estoque        INTEGER        NOT NULL DEFAULT 0 CHECK (estoque >= 0),
    cor_nome       VARCHAR(40),
    cor_hex        CHAR(7)        CHECK (cor_hex ~ '^#[0-9a-fA-F]{6}$'),
    genero         genero_produto,
    ativo          BOOLEAN        NOT NULL DEFAULT true,
    criado_em      TIMESTAMPTZ    NOT NULL DEFAULT now(),
    atualizado_em  TIMESTAMPTZ    NOT NULL DEFAULT now()
);
-- Atende a query de catálogo (categoria + paginação por id, só disponíveis)
CREATE INDEX IF NOT EXISTS ix_produtos_catalogo
    ON produtos (categoria_id, id) WHERE ativo AND estoque > 0;
CREATE INDEX IF NOT EXISTS ix_produtos_modalidade ON produtos (modalidade_id);

DROP TRIGGER IF EXISTS tg_produtos_atualizado_em ON produtos;
CREATE TRIGGER tg_produtos_atualizado_em
    BEFORE UPDATE ON produtos
    FOR EACH ROW EXECUTE FUNCTION set_atualizado_em();

DROP TRIGGER IF EXISTS tg_usuarios_atualizado_em ON usuarios;
CREATE TRIGGER tg_usuarios_atualizado_em
    BEFORE UPDATE ON usuarios
    FOR EACH ROW EXECUTE FUNCTION set_atualizado_em();

-- Tamanhos oferecidos por produto (o site usa PP, P, M, G, GG, XG)
CREATE TABLE IF NOT EXISTS produto_tamanhos (
    produto_id BIGINT     NOT NULL REFERENCES produtos(id) ON DELETE CASCADE,
    tamanho    VARCHAR(4) NOT NULL CHECK (tamanho IN ('PP','P','M','G','GG','XG')),
    PRIMARY KEY (produto_id, tamanho)
);

CREATE TABLE IF NOT EXISTS imagens_produto (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT       NOT NULL REFERENCES produtos(id) ON DELETE CASCADE,
    url        TEXT         NOT NULL,          -- caminho, URL ou data URL (foto enviada pelo admin)
    ordem      SMALLINT     NOT NULL DEFAULT 0,
    principal  BOOLEAN      NOT NULL DEFAULT false,
    criado_em  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
-- Bancos criados antes desta versão tinham url VARCHAR(500)
ALTER TABLE imagens_produto ALTER COLUMN url TYPE TEXT;
CREATE INDEX IF NOT EXISTS ix_imagens_produto ON imagens_produto (produto_id, ordem);
CREATE UNIQUE INDEX IF NOT EXISTS ux_imagens_principal
    ON imagens_produto (produto_id) WHERE principal;

-- Atributos extras (material, estação, gola...). Cor e tamanho são colunas próprias.
CREATE TABLE IF NOT EXISTS atributos (
    id        SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      VARCHAR(60) NOT NULL UNIQUE,
    tipo_dado tipo_dado_atributo NOT NULL DEFAULT 'texto',
    descricao VARCHAR(200),
    unidade   VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS produto_atributos (
    produto_id  BIGINT   NOT NULL REFERENCES produtos(id)  ON DELETE CASCADE,
    atributo_id SMALLINT NOT NULL REFERENCES atributos(id) ON DELETE RESTRICT,
    valor       VARCHAR(200) NOT NULL,
    PRIMARY KEY (produto_id, atributo_id)
);

-- ============================================================
-- Inteligência artificial (WearIA)
-- ============================================================
-- 1:1 com a imagem processada
CREATE TABLE IF NOT EXISTS processamentos_ia (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imagem_id            BIGINT       NOT NULL UNIQUE REFERENCES imagens_produto(id) ON DELETE CASCADE,
    bg_removido_url      VARCHAR(500),
    categoria_detectada  VARCHAR(40),
    cor_principal_hex    CHAR(7)      CHECK (cor_principal_hex ~ '^#[0-9a-fA-F]{6}$'),
    cores_secundarias    JSONB        NOT NULL DEFAULT '[]'::jsonb,
    embedding_clip       REAL[],                      -- vetor CLIP ViT-B/32 (512 posições)
    confianca            NUMERIC(5,4) CHECK (confianca BETWEEN 0 AND 1),
    modelo_ia            VARCHAR(80)  NOT NULL,       -- ex.: yolov8n-seg + clip-vit-base-patch32
    processado_em        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CHECK (embedding_clip IS NULL OR array_length(embedding_clip, 1) = 512)
);

CREATE TABLE IF NOT EXISTS favoritos (
    usuario_id BIGINT      NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    produto_id BIGINT      NOT NULL REFERENCES produtos(id) ON DELETE CASCADE,
    criado_em  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (usuario_id, produto_id)
);

CREATE TABLE IF NOT EXISTS estilo_preferencias (
    usuario_id    BIGINT   NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    estilo_id     SMALLINT NOT NULL REFERENCES estilos(id)  ON DELETE CASCADE,
    peso          SMALLINT NOT NULL DEFAULT 1 CHECK (peso BETWEEN 1 AND 10),
    registrado_em TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (usuario_id, estilo_id)
);

CREATE TABLE IF NOT EXISTS recomendacoes (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id             BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,   -- NULL = visitante
    produto_recomendado_id BIGINT NOT NULL REFERENCES produtos(id) ON DELETE CASCADE,
    produto_base_id        BIGINT REFERENCES produtos(id) ON DELETE CASCADE,   -- NULL = busca por foto
    tipo                   tipo_recomendacao NOT NULL,
    score                  NUMERIC(5,4) NOT NULL CHECK (score BETWEEN 0 AND 1),
    gerado_em              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CHECK (produto_base_id IS NULL OR produto_base_id <> produto_recomendado_id)
);
CREATE INDEX IF NOT EXISTS ix_recomendacoes_usuario ON recomendacoes (usuario_id, gerado_em DESC);

-- ============================================================
-- Vendas: cupons, pedidos, itens, pagamentos, entregas, NF
-- ============================================================
CREATE TABLE IF NOT EXISTS cupons (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo      VARCHAR(20)  NOT NULL UNIQUE CHECK (codigo = upper(codigo)),
    percentual  NUMERIC(5,4) NOT NULL CHECK (percentual > 0 AND percentual < 1),
    valido_de   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    valido_ate  TIMESTAMPTZ,
    uso_maximo  INTEGER      CHECK (uso_maximo > 0),
    ativo       BOOLEAN      NOT NULL DEFAULT true
);

-- Pedido em status 'aberto' funciona como o carrinho do cliente.
-- cliente_id aponta para usuarios (nome mantido da apresentação).
CREATE TABLE IF NOT EXISTS pedidos (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id    BIGINT        NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
    status        status_pedido NOT NULL DEFAULT 'aberto',
    cupom_id      BIGINT        REFERENCES cupons(id) ON DELETE RESTRICT,
    subtotal      NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    valor_frete   NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (valor_frete >= 0),
    desconto      NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (desconto >= 0),
    juros         NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (juros >= 0),
    total         NUMERIC(12,2) GENERATED ALWAYS AS
                      (subtotal + valor_frete - desconto + juros) STORED,
    criado_em     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    pago_em       TIMESTAMPTZ,
    cancelado_em  TIMESTAMPTZ,
    CHECK (desconto <= subtotal),
    CHECK ((status IN ('pago', 'enviado', 'entregue')) = (pago_em IS NOT NULL)
           OR status = 'cancelado')
);
CREATE INDEX IF NOT EXISTS ix_pedidos_cliente ON pedidos (cliente_id, criado_em DESC, id DESC);
CREATE INDEX IF NOT EXISTS ix_pedidos_pagos   ON pedidos (pago_em) WHERE status = 'pago';
-- Um único carrinho (pedido aberto) por cliente
CREATE UNIQUE INDEX IF NOT EXISTS ux_pedidos_aberto
    ON pedidos (cliente_id) WHERE status = 'aberto';

-- O site permite o mesmo produto em tamanhos diferentes no carrinho,
-- por isso a unicidade inclui o tamanho.
CREATE TABLE IF NOT EXISTS itens_pedido (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id      BIGINT        NOT NULL REFERENCES pedidos(id)  ON DELETE CASCADE,
    produto_id     BIGINT        NOT NULL REFERENCES produtos(id) ON DELETE RESTRICT,
    tamanho        VARCHAR(4)    NOT NULL CHECK (tamanho IN ('PP','P','M','G','GG','XG')),
    quantidade     INTEGER       NOT NULL CHECK (quantidade > 0),
    preco_unitario NUMERIC(12,2) NOT NULL CHECK (preco_unitario > 0),
    UNIQUE (pedido_id, produto_id, tamanho)
);
CREATE INDEX IF NOT EXISTS ix_itens_produto ON itens_pedido (produto_id);

CREATE TABLE IF NOT EXISTS pagamentos (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id     BIGINT           NOT NULL REFERENCES pedidos(id) ON DELETE RESTRICT,
    metodo        metodo_pagamento NOT NULL,
    status        status_pagamento NOT NULL DEFAULT 'pendente',
    valor         NUMERIC(12,2)    NOT NULL CHECK (valor > 0),
    parcelas      SMALLINT         NOT NULL DEFAULT 1 CHECK (parcelas BETWEEN 1 AND 12),
    taxa_juros_mensal NUMERIC(6,4) NOT NULL DEFAULT 0 CHECK (taxa_juros_mensal >= 0),
    id_transacao_gateway VARCHAR(100) UNIQUE,   -- referência do gateway; nunca guardar dados do cartão
    criado_em     TIMESTAMPTZ      NOT NULL DEFAULT now(),
    confirmado_em TIMESTAMPTZ,
    CHECK (metodo = 'credito' OR parcelas = 1)
);
CREATE INDEX IF NOT EXISTS ix_pagamentos_pedido ON pagamentos (pedido_id);
-- No máximo um pagamento aprovado por pedido
CREATE UNIQUE INDEX IF NOT EXISTS ux_pagamentos_aprovado
    ON pagamentos (pedido_id) WHERE status = 'aprovado';

-- Endereço copiado no momento da compra: mudanças futuras no
-- cadastro do cliente não alteram o histórico da entrega.
CREATE TABLE IF NOT EXISTS entregas (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id         BIGINT        NOT NULL UNIQUE REFERENCES pedidos(id) ON DELETE CASCADE,
    endereco_id       BIGINT        REFERENCES enderecos(id) ON DELETE SET NULL,
    destinatario      VARCHAR(150)  NOT NULL,
    logradouro        VARCHAR(200)  NOT NULL,
    numero            VARCHAR(20)   NOT NULL,
    complemento       VARCHAR(100),
    bairro            VARCHAR(100)  NOT NULL,
    cidade            VARCHAR(100)  NOT NULL,
    estado            CHAR(2)       NOT NULL CHECK (estado ~ '^[A-Z]{2}$'),
    cep               CHAR(8)       NOT NULL CHECK (cep ~ '^[0-9]{8}$'),
    tipo              tipo_entrega  NOT NULL DEFAULT 'padrao',
    distancia_km      NUMERIC(8,2)  CHECK (distancia_km >= 0),
    valor_frete       NUMERIC(12,2) NOT NULL CHECK (valor_frete >= 0),
    prazo_dias        SMALLINT      CHECK (prazo_dias >= 0),
    transportadora    VARCHAR(100),
    codigo_rastreio   VARCHAR(60)   UNIQUE,
    status            status_entrega NOT NULL DEFAULT 'aguardando_envio',
    enviado_em        TIMESTAMPTZ,
    entregue_em       TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS notas_fiscais (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id     BIGINT        NOT NULL UNIQUE REFERENCES pedidos(id) ON DELETE RESTRICT,
    numero        INTEGER       NOT NULL,
    serie         SMALLINT      NOT NULL DEFAULT 1,
    chave_acesso  CHAR(44)      UNIQUE CHECK (chave_acesso ~ '^[0-9]{44}$'),
    valor_total   NUMERIC(12,2) NOT NULL CHECK (valor_total >= 0),
    valor_icms    NUMERIC(12,2) NOT NULL DEFAULT 0,
    valor_pis     NUMERIC(12,2) NOT NULL DEFAULT 0,
    valor_cofins  NUMERIC(12,2) NOT NULL DEFAULT 0,
    emitida_em    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    UNIQUE (serie, numero)
);

COMMIT;
