-- ============================================================
-- Tech Wear — Dados iniciais
-- Catálogo gerado de js/produtos.js (PRODUTOS_PADRAO, 33 produtos).
-- Ids dos produtos iguais aos do site. Script idempotente.
-- ============================================================

SET client_min_messages = warning;
BEGIN;

INSERT INTO papeis (nome, descricao) VALUES
    ('admin',   'Gerencia catálogo, preços, estoque e pedidos'),
    ('cliente', 'Compra na loja e usa a WearIA')
ON CONFLICT (nome) DO NOTHING;

INSERT INTO categorias (slug, nome) VALUES
    ('camisetas', 'Camisetas'),
    ('calcas',    'Calças'),
    ('jaquetas',  'Jaquetas'),
    ('moletons',  'Moletons'),
    ('shorts',    'Shorts')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO modalidades (slug, nome, descricao) VALUES
    ('corrida',  'Corrida',  NULL),
    ('basquete', 'Basquete', NULL),
    ('academia', 'Academia', NULL),
    ('todos',    'Multiesporte', 'Peças para qualquer modalidade')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO estilos (slug, nome) VALUES
    ('casual',    'Casual'),
    ('streetwear','Streetwear'),
    ('performance','Performance'),
    ('retro',     'Retrô')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO atributos (nome, tipo_dado, unidade) VALUES
    ('Material',         'texto',  NULL),
    ('Estação',          'texto',  NULL),
    ('Tipo de Manga',    'texto',  NULL),
    ('Gola',             'texto',  NULL),
    ('Comprimento',      'texto',  NULL),
    ('Elasticidade',     'texto',  NULL),
    ('Peso do Tecido',   'numero', 'g/m²'),
    ('Respirabilidade',  'texto',  NULL),
    ('Proteção UV',      'numero', 'FPU')
ON CONFLICT (nome) DO NOTHING;

-- Cupons usados hoje em pagamento.html
INSERT INTO cupons (codigo, percentual) VALUES
    ('TECWEAR10',      0.10),
    ('DESCONTO15',     0.15),
    ('PRIMEIRACOMPRA', 0.20)
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO produtos
    (id, sku, nome, descricao, categoria_id, modalidade_id, preco, estoque, cor_nome, cor_hex)
VALUES
    (1, 'CAM-0001', 'Camiseta Essential Branca', 'Camiseta de algodão penteado com toque macio e caimento reto, básica para treino e dia a dia.',
     (SELECT id FROM categorias WHERE slug = 'camisetas'),
     (SELECT id FROM modalidades WHERE slug = 'academia'),
     79.90, 48, 'Branco', '#eeefef'),
    (2, 'CAM-0002', 'Camiseta Dry-Fit Preta', 'Tecido dry-fit que afasta o suor da pele e seca rápido. Estampa circular discreta no peito.',
     (SELECT id FROM categorias WHERE slug = 'camisetas'),
     (SELECT id FROM modalidades WHERE slug = 'academia'),
     89.90, 40, 'Preto', '#111111'),
    (3, 'CAM-0003', 'Camiseta Performance Vermelha', 'Malha leve com proteção UV 50+ e costuras planas para corridas longas sem atrito.',
     (SELECT id FROM categorias WHERE slug = 'camisetas'),
     (SELECT id FROM modalidades WHERE slug = 'corrida'),
     99.90, 32, 'Vermelho', '#cc011e'),
    (4, 'CAM-0004', 'Camiseta Run Amarela', 'Cor de alta visibilidade para treinos ao ar livre, com tecido respirável e secagem rápida.',
     (SELECT id FROM categorias WHERE slug = 'camisetas'),
     (SELECT id FROM modalidades WHERE slug = 'corrida'),
     94.90, 26, 'Amarelo', '#eee373'),
    (5, 'CAM-0005', 'Regata Basquete Creme', 'Regata de basquete em mesh com acabamento em ribana e número aplicado nas costas.',
     (SELECT id FROM categorias WHERE slug = 'camisetas'),
     (SELECT id FROM modalidades WHERE slug = 'basquete'),
     149.90, 18, 'Bege', '#d9cfae'),
    (6, 'CAM-0006', 'Regata Basquete Marinho', 'Regata de quadra em mesh leve com recortes laterais para ventilação.',
     (SELECT id FROM categorias WHERE slug = 'camisetas'),
     (SELECT id FROM modalidades WHERE slug = 'basquete'),
     149.90, 20, 'Azul Marinho', '#1b2440'),
    (7, 'CAM-0007', 'Camiseta Fitness Verde', 'Modelagem feminina levemente ajustada, tecido com elastano para liberdade de movimento.',
     (SELECT id FROM categorias WHERE slug = 'camisetas'),
     (SELECT id FROM modalidades WHERE slug = 'academia'),
     89.90, 30, 'Verde', '#5f7a72'),
    (8, 'CAM-0008', 'Camiseta Training Azul', 'Cropped de treino com recortes em mesh e tecido de compressão leve.',
     (SELECT id FROM categorias WHERE slug = 'camisetas'),
     (SELECT id FROM modalidades WHERE slug = 'academia'),
     99.90, 22, 'Azul', '#4b5ba6'),
    (9, 'CAL-0009', 'Legging Compressão Preta', 'Legging de cintura alta com compressão média, não fica transparente no agachamento.',
     (SELECT id FROM categorias WHERE slug = 'calcas'),
     (SELECT id FROM modalidades WHERE slug = 'academia'),
     159.90, 35, 'Preto', '#111111'),
    (10, 'CAL-0010', 'Calça Moletom Cinza', 'Moletom flanelado por dentro, cós com cordão e bolsos laterais. Conforto para o pós-treino.',
     (SELECT id FROM categorias WHERE slug = 'calcas'),
     (SELECT id FROM modalidades WHERE slug = 'academia'),
     169.90, 28, 'Cinza', '#c2c3c5'),
    (11, 'CAL-0011', 'Calça Jogger Turquesa', 'Jogger leve com punho na barra e cós elástico, ideal para aquecimento e trote.',
     (SELECT id FROM categorias WHERE slug = 'calcas'),
     (SELECT id FROM modalidades WHERE slug = 'corrida'),
     179.90, 16, 'Azul', '#40a7c1'),
    (12, 'CAL-0012', 'Calça Jogger Cáqui', 'Sarja com elastano, punho na barra e bolsos funcionais. Vai do treino à rua.',
     (SELECT id FROM categorias WHERE slug = 'calcas'),
     (SELECT id FROM modalidades WHERE slug = 'corrida'),
     189.90, 24, 'Bege', '#a08c6c'),
    (13, 'CAL-0013', 'Calça Track Listrada', 'Calça de agasalho com listras laterais contrastantes e zíper no tornozelo.',
     (SELECT id FROM categorias WHERE slug = 'calcas'),
     (SELECT id FROM modalidades WHERE slug = 'corrida'),
     199.90, 20, 'Preto', '#121417'),
    (14, 'CAL-0014', 'Calça Jogger Roxa', 'Moletom leve com bolsos e punho elástico, cor vibrante para o treino.',
     (SELECT id FROM categorias WHERE slug = 'calcas'),
     (SELECT id FROM modalidades WHERE slug = 'academia'),
     179.90, 14, 'Roxo', '#492854'),
    (15, 'JAQ-0015', 'Jaqueta Corta-Vento Tricolor', 'Corta-vento repelente à água com capuz embutido e blocos de cor preto, branco e amarelo.',
     (SELECT id FROM categorias WHERE slug = 'jaquetas'),
     (SELECT id FROM modalidades WHERE slug = 'corrida'),
     299.90, 15, 'Preto', '#1a1b1b'),
    (16, 'JAQ-0016', 'Jaqueta Bomber Marinho', 'Bomber acolchoada com gola forrada em pelúcia e punhos canelados.',
     (SELECT id FROM categorias WHERE slug = 'jaquetas'),
     (SELECT id FROM modalidades WHERE slug = 'todos'),
     349.90, 12, 'Azul Marinho', '#2e3d57'),
    (17, 'JAQ-0017', 'Jaqueta Track Vermelha', 'Jaqueta de agasalho com zíper frontal e listras brancas nas mangas.',
     (SELECT id FROM categorias WHERE slug = 'jaquetas'),
     (SELECT id FROM modalidades WHERE slug = 'corrida'),
     279.90, 18, 'Vermelho', '#c82d2d'),
    (18, 'JAQ-0018', 'Jaqueta Puffer Amarela', 'Puffer volumosa com enchimento térmico leve, gola alta e acabamento brilhante.',
     (SELECT id FROM categorias WHERE slug = 'jaquetas'),
     (SELECT id FROM modalidades WHERE slug = 'todos'),
     449.90, 10, 'Amarelo', '#f2c12e'),
    (19, 'JAQ-0019', 'Jaqueta Puffer Laranja', 'Puffer com capuz e gomos largos, quente e leve para dias frios.',
     (SELECT id FROM categorias WHERE slug = 'jaquetas'),
     (SELECT id FROM modalidades WHERE slug = 'todos'),
     449.90, 9, 'Laranja', '#d2691e'),
    (20, 'JAQ-0020', 'Jaqueta Puffer Off-White', 'Puffer oversized em tom off-white com gola alta e bolsos com zíper.',
     (SELECT id FROM categorias WHERE slug = 'jaquetas'),
     (SELECT id FROM modalidades WHERE slug = 'todos'),
     469.90, 8, 'Branco', '#e8e6dc'),
    (21, 'JAQ-0021', 'Jaqueta Retrô Lilás', 'Corta-vento estilo anos 90 em nylon com recortes coloridos e capuz.',
     (SELECT id FROM categorias WHERE slug = 'jaquetas'),
     (SELECT id FROM modalidades WHERE slug = 'corrida'),
     319.90, 11, 'Lilás', '#7f7fc4'),
    (22, 'MOL-0022', 'Moletom Cinza Mescla', 'Moletom canguru com capuz forrado e bolso frontal, peso médio.',
     (SELECT id FROM categorias WHERE slug = 'moletons'),
     (SELECT id FROM modalidades WHERE slug = 'academia'),
     229.90, 30, 'Cinza', '#d5dde0'),
    (23, 'MOL-0023', 'Moletom Verde Floresta', 'Capuz com cordão, punhos canelados e bordado discreto no peito.',
     (SELECT id FROM categorias WHERE slug = 'moletons'),
     (SELECT id FROM modalidades WHERE slug = 'todos'),
     239.90, 22, 'Verde Militar', '#1e4a42'),
    (24, 'MOL-0024', 'Moletom Rosa Oversized', 'Modelagem ampla e ombro caído em moletom felpado macio.',
     (SELECT id FROM categorias WHERE slug = 'moletons'),
     (SELECT id FROM modalidades WHERE slug = 'todos'),
     259.90, 16, 'Rosa', '#f7b8e0'),
    (25, 'MOL-0025', 'Moletom Branco Basic', 'O moletom básico: capuz, bolso canguru e algodão encorpado.',
     (SELECT id FROM categorias WHERE slug = 'moletons'),
     (SELECT id FROM modalidades WHERE slug = 'todos'),
     219.90, 25, 'Branco', '#e6e6e6'),
    (26, 'MOL-0026', 'Moletom Bege Areia', 'Tom neutro areia, capuz amplo e interior flanelado.',
     (SELECT id FROM categorias WHERE slug = 'moletons'),
     (SELECT id FROM modalidades WHERE slug = 'todos'),
     239.90, 20, 'Bege', '#cdb3a5'),
    (27, 'MOL-0027', 'Moletom Preto Essential', 'Moletom preto com capuz e bolso canguru, combina com tudo.',
     (SELECT id FROM categorias WHERE slug = 'moletons'),
     (SELECT id FROM modalidades WHERE slug = 'todos'),
     229.90, 34, 'Preto', '#181618'),
    (28, 'SHO-0028', 'Shorts Basquete Amarelo', 'Shorts de basquete em mesh com cós elástico largo e comprimento até o joelho.',
     (SELECT id FROM categorias WHERE slug = 'shorts'),
     (SELECT id FROM modalidades WHERE slug = 'basquete'),
     129.90, 24, 'Amarelo', '#f2c200'),
    (29, 'SHO-0029', 'Shorts Tactel Água', 'Tactel leve com forro interno e secagem rápida.',
     (SELECT id FROM categorias WHERE slug = 'shorts'),
     (SELECT id FROM modalidades WHERE slug = 'corrida'),
     99.90, 30, 'Azul', '#48d1d6'),
    (30, 'SHO-0030', 'Shorts Academia Vermelho', 'Shorts de treino com tecido elástico em 4 direções para agachamento e levantamento.',
     (SELECT id FROM categorias WHERE slug = 'shorts'),
     (SELECT id FROM modalidades WHERE slug = 'academia'),
     109.90, 28, 'Vermelho', '#c0262c'),
    (31, 'SHO-0031', 'Shorts Corrida Laranja', 'Shorts de corrida com bermuda interna de compressão e bolso para chave.',
     (SELECT id FROM categorias WHERE slug = 'shorts'),
     (SELECT id FROM modalidades WHERE slug = 'corrida'),
     119.90, 18, 'Laranja', '#e8622c'),
    (32, 'SHO-0032', 'Shorts Fitness Grafite', 'Shorts soltinho com cós alto e laterais abertas para mais mobilidade.',
     (SELECT id FROM categorias WHERE slug = 'shorts'),
     (SELECT id FROM modalidades WHERE slug = 'academia'),
     109.90, 20, 'Cinza', '#4b4250'),
    (33, 'SHO-0033', 'Shorts Basquete Preto', 'Shorts de quadra em mesh duplo com faixa lateral contrastante.',
     (SELECT id FROM categorias WHERE slug = 'shorts'),
     (SELECT id FROM modalidades WHERE slug = 'basquete'),
     129.90, 26, 'Preto', '#1a1a1a')
ON CONFLICT (id) DO NOTHING;

-- Próximo produto criado pelo admin continua do 34
SELECT setval(pg_get_serial_sequence('produtos', 'id'), (SELECT MAX(id) FROM produtos));

INSERT INTO produto_tamanhos (produto_id, tamanho) VALUES
    (1, 'P'),
    (1, 'M'),
    (1, 'G'),
    (1, 'GG'),
    (1, 'XG'),
    (2, 'P'),
    (2, 'M'),
    (2, 'G'),
    (2, 'GG'),
    (2, 'XG'),
    (3, 'P'),
    (3, 'M'),
    (3, 'G'),
    (3, 'GG'),
    (4, 'P'),
    (4, 'M'),
    (4, 'G'),
    (4, 'GG'),
    (5, 'M'),
    (5, 'G'),
    (5, 'GG'),
    (5, 'XG'),
    (6, 'M'),
    (6, 'G'),
    (6, 'GG'),
    (6, 'XG'),
    (7, 'PP'),
    (7, 'P'),
    (7, 'M'),
    (7, 'G'),
    (8, 'PP'),
    (8, 'P'),
    (8, 'M'),
    (8, 'G'),
    (9, 'PP'),
    (9, 'P'),
    (9, 'M'),
    (9, 'G'),
    (9, 'GG'),
    (10, 'P'),
    (10, 'M'),
    (10, 'G'),
    (10, 'GG'),
    (11, 'P'),
    (11, 'M'),
    (11, 'G'),
    (11, 'GG'),
    (12, 'P'),
    (12, 'M'),
    (12, 'G'),
    (12, 'GG'),
    (13, 'P'),
    (13, 'M'),
    (13, 'G'),
    (13, 'GG'),
    (14, 'P'),
    (14, 'M'),
    (14, 'G'),
    (15, 'P'),
    (15, 'M'),
    (15, 'G'),
    (15, 'GG'),
    (16, 'P'),
    (16, 'M'),
    (16, 'G'),
    (16, 'GG'),
    (17, 'P'),
    (17, 'M'),
    (17, 'G'),
    (17, 'GG'),
    (18, 'P'),
    (18, 'M'),
    (18, 'G'),
    (19, 'M'),
    (19, 'G'),
    (19, 'GG'),
    (20, 'P'),
    (20, 'M'),
    (20, 'G'),
    (21, 'P'),
    (21, 'M'),
    (21, 'G'),
    (21, 'GG'),
    (22, 'P'),
    (22, 'M'),
    (22, 'G'),
    (22, 'GG'),
    (23, 'P'),
    (23, 'M'),
    (23, 'G'),
    (23, 'GG'),
    (24, 'P'),
    (24, 'M'),
    (24, 'G'),
    (25, 'P'),
    (25, 'M'),
    (25, 'G'),
    (25, 'GG'),
    (25, 'XG'),
    (26, 'P'),
    (26, 'M'),
    (26, 'G'),
    (26, 'GG'),
    (27, 'P'),
    (27, 'M'),
    (27, 'G'),
    (27, 'GG'),
    (27, 'XG'),
    (28, 'P'),
    (28, 'M'),
    (28, 'G'),
    (28, 'GG'),
    (29, 'P'),
    (29, 'M'),
    (29, 'G'),
    (29, 'GG'),
    (30, 'P'),
    (30, 'M'),
    (30, 'G'),
    (30, 'GG'),
    (31, 'PP'),
    (31, 'P'),
    (31, 'M'),
    (31, 'G'),
    (32, 'PP'),
    (32, 'P'),
    (32, 'M'),
    (32, 'G'),
    (33, 'P'),
    (33, 'M'),
    (33, 'G'),
    (33, 'GG')
ON CONFLICT DO NOTHING;

INSERT INTO imagens_produto (produto_id, url, ordem, principal)
SELECT v.produto_id, v.url, 0, true
FROM (VALUES
    (1, 'img/produtos/camiseta-essential-branca.jpg'),
    (2, 'img/produtos/camiseta-dry-fit-preta.jpg'),
    (3, 'img/produtos/camiseta-performance-vermelha.jpg'),
    (4, 'img/produtos/camiseta-run-amarela.jpg'),
    (5, 'img/produtos/regata-basquete-creme.jpg'),
    (6, 'img/produtos/regata-basquete-marinho.jpg'),
    (7, 'img/produtos/camiseta-fitness-verde.jpg'),
    (8, 'img/produtos/camiseta-training-azul.jpg'),
    (9, 'img/produtos/legging-compressao-preta.jpg'),
    (10, 'img/produtos/calca-moletom-cinza.jpg'),
    (11, 'img/produtos/calca-jogger-turquesa.jpg'),
    (12, 'img/produtos/calca-jogger-caqui.jpg'),
    (13, 'img/produtos/calca-track-listrada.jpg'),
    (14, 'img/produtos/calca-jogger-roxa.jpg'),
    (15, 'img/produtos/jaqueta-corta-vento-tricolor.jpg'),
    (16, 'img/produtos/jaqueta-bomber-marinho.jpg'),
    (17, 'img/produtos/jaqueta-track-vermelha.jpg'),
    (18, 'img/produtos/jaqueta-puffer-amarela.jpg'),
    (19, 'img/produtos/jaqueta-puffer-laranja.jpg'),
    (20, 'img/produtos/jaqueta-puffer-off-white.jpg'),
    (21, 'img/produtos/jaqueta-retro-lilas.jpg'),
    (22, 'img/produtos/moletom-cinza-mescla.jpg'),
    (23, 'img/produtos/moletom-verde-floresta.jpg'),
    (24, 'img/produtos/moletom-rosa-oversized.jpg'),
    (25, 'img/produtos/moletom-branco-basic.jpg'),
    (26, 'img/produtos/moletom-bege-areia.jpg'),
    (27, 'img/produtos/moletom-preto-essential.jpg'),
    (28, 'img/produtos/shorts-basquete-amarelo.jpg'),
    (29, 'img/produtos/shorts-tactel-agua.jpg'),
    (30, 'img/produtos/shorts-academia-vermelho.jpg'),
    (31, 'img/produtos/shorts-corrida-laranja.jpg'),
    (32, 'img/produtos/shorts-fitness-grafite.jpg'),
    (33, 'img/produtos/shorts-basquete-preto.jpg')
) AS v(produto_id, url)
WHERE NOT EXISTS (SELECT 1 FROM imagens_produto i WHERE i.produto_id = v.produto_id AND i.principal);

COMMIT;
